import express from "express";
import cors from "cors";
import { createConnection } from "typeorm";
import bodyParser from "body-parser";
import morgan from "morgan";
import * as dotenv from "dotenv";
import swaggerUI from "swagger-ui-express";
import productRouter from "./routes/product.route";
// import generateData from "./utils/autoGenerateData";
import userRouter from "./routes/user.route";

const port = parseInt(process.env.PORT) || 8080;

const main = async () => {
  await createConnection();

  const app = express();
  const swaggerDocument = require("../swagger.json");

  app.use("/api-docs", swaggerUI.serve, swaggerUI.setup(swaggerDocument));

  app.use(cors());
  app.use(express.json());
  app.use(morgan("dev"));
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({ extended: true }));
  dotenv.config();

  // generateData();

  app.get("/", (_, res) => {
    res.send("Hello World!");
  });

  app.use("/api/v1/products", productRouter);
  app.use("/api/v1/users", userRouter);

  app.listen(port, () => {
    return console.log(`Express is listening at http://localhost:${port}`);
  });
};

main().catch((err) => console.log(err));
